In [1]:
import pandas as pd

print("Pandas Imported Successfully")

Pandas Imported Successfully

In [2]:
import pandas as pd

data = {
    "Sensor_ID": [101, 102, 103, 103, 104, 105],
    "Temperature": [28.5, None, 30.2, 30.2, 27.8, 31.0],
    "Humidity": [65, 60, None, None, 70, 55],
    "Location": ["Room1", "Room2", "Room3", "Room3", "Room1", "Room2"]
}

df = pd.DataFrame(data)

df

   Sensor_ID  Temperature  Humidity Location
0        101         28.5      65.0    Room1
1        102          NaN      60.0    Room2
2        103         30.2       NaN    Room3
3        103         30.2       NaN    Room3
4        104         27.8      70.0    Room1
5        105         31.0      55.0    Room2

In [3]:
df.to_csv("raw_sensor_data.csv", index=False)

print("Raw Dataset Saved Successfully")

Raw Dataset Saved Successfully

In [4]:
df = pd.read_csv("raw_sensor_data.csv")

print("Original Dataset")
df

Original Dataset

   Sensor_ID  Temperature  Humidity Location
0        101         28.5      65.0    Room1
1        102          NaN      60.0    Room2
2        103         30.2       NaN    Room3
3        103         30.2       NaN    Room3
4        104         27.8      70.0    Room1
5        105         31.0      55.0    Room2

In [5]:
print("Missing Values in Each Column")

df.isnull().sum()

Missing Values in Each Column

Sensor_ID      0
Temperature    1
Humidity       2
Location       0
dtype: int64

In [6]:
df["Temperature"] = df["Temperature"].fillna(df["Temperature"].mean())

df["Humidity"] = df["Humidity"].fillna(df["Humidity"].mean())

print("Missing Values Filled Successfully")

df

Missing Values Filled Successfully

   Sensor_ID  Temperature  Humidity Location
0        101        28.50      65.0    Room1
1        102        29.54      60.0    Room2
2        103        30.20      62.5    Room3
3        103        30.20      62.5    Room3
4        104        27.80      70.0    Room1
5        105        31.00      55.0    Room2

In [7]:
df = df.drop_duplicates()

print("Duplicate Rows Removed Successfully")

df

Duplicate Rows Removed Successfully

   Sensor_ID  Temperature  Humidity Location
0        101        28.50      65.0    Room1
1        102        29.54      60.0    Room2
2        103        30.20      62.5    Room3
4        104        27.80      70.0    Room1
5        105        31.00      55.0    Room2

In [8]:
print("Dataset Shape:")

df.shape

Dataset Shape:

(5, 4)

In [9]:
df["Temperature_Status"] = df["Temperature"].apply(
    lambda x: "High" if x > 30 else "Normal"
)

print("Feature Extraction Completed")

df

Feature Extraction Completed

   Sensor_ID  Temperature  Humidity Location Temperature_Status
0        101        28.50      65.0    Room1             Normal
1        102        29.54      60.0    Room2             Normal
2        103        30.20      62.5    Room3               High
4        104        27.80      70.0    Room1             Normal
5        105        31.00      55.0    Room2               High

In [10]:
df.to_csv("cleaned_sensor_data.csv", index=False)

print("Cleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

# Week 4: Data Cleaning and Transformation

## Objective
Perform data cleaning and preprocessing using Pandas.

## Tasks Completed
- Created a raw sensor dataset
- Handled missing values
- Removed duplicate records
- Performed feature extraction
- Saved the cleaned dataset

## Files
- data_cleaning_transformation.ipynb
- raw_sensor_data.csv
- cleaned_sensor_data.csv

## Tools Used
- Python
- Pandas
- Jupyter Notebook
- VS Code