In [1]:
import pandas as pd
import json
import requests

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [2]:
sensor_data = {
    "Sensor_ID": [101, 102, 103, 104, 105],
    "Temperature": [28.5, 29.1, 30.2, 27.8, 31.0],
    "Humidity": [65, 60, 58, 70, 55]
}

df = pd.DataFrame(sensor_data)

df

   Sensor_ID  Temperature  Humidity
0        101         28.5        65
1        102         29.1        60
2        103         30.2        58
3        104         27.8        70
4        105         31.0        55

In [3]:
df.to_csv("sensor_data.csv", index=False)

print("CSV File Saved Successfully")

CSV File Saved Successfully

In [4]:
csv_data = pd.read_csv("sensor_data.csv")

csv_data

   Sensor_ID  Temperature  Humidity
0        101         28.5        65
1        102         29.1        60
2        103         30.2        58
3        104         27.8        70
4        105         31.0        55

In [5]:
df.to_json("sensor_data.json", orient="records", indent=4)

print("JSON File Created Successfully")

JSON File Created Successfully

In [6]:
import json

with open("sensor_data.json", "r") as file:
    data = json.load(file)

print(data)

[{'Sensor_ID': 101, 'Temperature': 28.5, 'Humidity': 65}, {'Sensor_ID': 102, 'Temperature': 29.1, 'Humidity': 60}, {'Sensor_ID': 103, 'Temperature': 30.2, 'Humidity': 58}, {'Sensor_ID': 104, 'Temperature': 27.8, 'Humidity': 70}, {'Sensor_ID': 105, 'Temperature': 31.0, 'Humidity': 55}]

In [7]:
import requests

url = "https://jsonplaceholder.typicode.com/posts/1"

response = requests.get(url)

print("Status Code:", response.status_code)
print(response.json())

Status Code: 200
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [8]:
{
 'userId':1,
 'id':1,
 'title':'...',
 'body':'...'
}

{'userId': 1, 'id': 1, 'title': '...', 'body': '...'}

In [9]:
print("Sensor Logs")
print(df)

Sensor Logs
   Sensor_ID  Temperature  Humidity
0        101         28.5        65
1        102         29.1        60
2        103         30.2        58
3        104         27.8        70
4        105         31.0        55

# Week 3: Data Collection from IoT Devices

## Objectives
- Create sample IoT sensor data.
- Store data in CSV format.
- Convert data into JSON format.
- Read CSV and JSON files.
- Simulate API-based data collection.
- Display sensor logs.